// All native DOM events that work with document-level event delegation
// SEE: https://developer.mozilla.org/en-US/docs/Web/Events
//
// INCLUDED: Events that bubble OR can be captured via document listeners
// - Most events bubble naturally and work with event delegation
// - Some events (load, resize, scroll, etc.) don't bubble but can be captured
// - Document-level listeners with capture=true work for all these events
//
// EXCLUDED (don't work with document-level delegation):
// - focus/blur: Use focusin/focusout instead (which do bubble)
// - mouseenter/mouseleave: Use mouseover/mouseout instead (which do bubble)

export const nativeDelegatableEvents = [
  'DOMContentLoaded',
  'abort',
  'animationcancel',
  'animationend',
  'animationiteration',
  'animationstart',
  'auxclick',
  'beforeunload',
  'canplay',
  'canplaythrough',
  'change',
  'click',
  'compositionend',
  'compositionstart',
  'compositionupdate',
  'contextmenu',
  'copy',
  'cut',
  'dblclick',
  'drag',
  'dragend',
  'dragenter',
  'dragleave',
  'dragover',
  'dragstart',
  'drop',
  'durationchange',
  'emptied',
  'ended',
  'error',
  'focusin',
  'focusout',
  'fullscreenchange',
  'fullscreenerror',
  'hashchange',
  'input',
  'keydown',
  'keyup',
  'load',
  'loadeddata',
  'loadedmetadata',
  'loadstart',
  'mousedown',
  'mousemove',
  'mouseout',
  'mouseover',
  'mouseup',
  'orientationchange',
  'paste',
  'pause',
  'play',
  'playing',
  'pointercancel',
  'pointerdown',
  'pointerlockchange',
  'pointerlockerror',
  'pointermove',
  'pointerout',
  'pointerover',
  'pointerup',
  'popstate',
  'progress',
  'ratechange',
  'reset',
  'resize',
  'scroll',
  'seeked',
  'seeking',
  'select',
  'stalled',
  'submit',
  'suspend',
  'timeupdate',
  'touchcancel',
  'touchend',
  'touchmove',
  'touchstart',
  'transitioncancel',
  'transitionend',
  'transitionrun',
  'transitionstart',
  'unload',
  'visibilitychange',
  'volumechange',
  'waiting',
  'wheel',
]

// Events that can be listened to on window
// Some are window-only, others also work with document delegation
export const nativeWindowEvents = [
  'afterprint',
  'appinstalled',
  'beforeinstallprompt',
  'beforeprint',
  'beforeunload',
  'blur',
  'devicemotion',
  'deviceorientation',
  'deviceorientationabsolute',
  'focus',
  'gamepadconnected',
  'gamepaddisconnected',
  'hashchange',
  'languagechange',
  'load',
  'message',
  'messageerror',
  'offline',
  'online',
  'pagehide',
  'pageshow',
  'pageswap',
  'popstate',
  'rejectionhandled',
  'resize',
  'scroll',
  'scrollsnapchange',
  'scrollsnapchanging',
  'storage',
  'unhandledrejection',
  'unload',
  'visibilitychange',
]
